### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/biapol-utilities#25]
We should create a minimal documentation. E.g. the readme should say what this library is doing and list all functions that are publicly available. Links to notebooks for more details would be great as well. See the [pyclesperanto example gallery](https://github.com/clEsperanto/pyclesperanto_prototype#example-gallery) for an example of how this could be done without much effort. In the future, we should not merge new functions without the new function being linked in the documentation.

**Comment by jo-mueller** [comment]
Hi @haesleinhuepf ,

I am currently working on documentation pages [here](https://github.com/BiAPoL/biapol-utilities/tree/create-sphinx-doc) and I am fairly content with how it is coming out. The documentation pages can be found at `_doc/_build/html/index.html`.

Afaik, these fies could be copied relatively easily to readthedocs.io. I moved the notebooks to the doc part for this purpose. 

Let me know what you think!
