### ISSUE TITLE
Check public API

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/biapol-utilities#28]
Hi Johannes @jo-mueller ,

before releasing the first version to pypi, could you please carefully check that the public API is as you want it to be? At the moment, all functions in `biapol_utilities.label` are also available in `biapol_utilities` directly because of [this line](https://github.com/BiAPoL/biapol-utilities/blob/main/biapol_utilities/__init__.py#L19). Hence, these two lines do the same:

```
biapol_utilitis.label.compare_labels(a, b)
biapol_utilitis.compare_labels(a, b)
```

Is this intentional? If so, why? If not, consider either renaming "label" to "_label" or remove the line linked above, depending on how you want the public API to be.

Thanks!

Best,
Robert

**Comment by jo-mueller** [comment]
> Is this intentional?

Absolutely not^^ I thought I'd need the mid-level __init__.py to "broadcast" the subpackages (label, data, etc) to biapol_utilities, but apparently that's not necessary?

**Comment by haesleinhuepf** [comment]
I _think_ the `label` sub-package is public already. You can make it private if you add an underscore.

**Comment by jo-mueller** [comment]
So I would keep the __init__.py files as they are now and rename label to _label?

**Comment by haesleinhuepf** [comment]
> I would prefer to keep this call rather than `biapol_utilitis.compare_labels(a, b)`.

Then you need to remove [this line](https://github.com/BiAPoL/biapol-utilities/blob/main/biapol_utilities/__init__.py#L19) as mentioned above.

**Comment by jo-mueller** [comment]
I changed it in PR #30 . Deleting the import in this __init__.py alltogether didn't work for me, though.
