### ISSUE TITLE
Visualization module

### ISSUE THREAD

**Issue by jo-mueller** [BiAPoL/biapol-utilities#38]
I was wondering whether it could make sense to add a new module to the utilities that provides **visualizations ** we use a lot. 

From the top of my head, I would think of, for instance, Bland-Altman plots for method comparison. 

Functions in such a module should return matplotlib figure instance so figures can easily be saved or edited. The inputs would depend of the respective visualization.

@haesleinhuepf @zoccoler What do you think of this? Is this a useful idea or will such implementations always fail to cover the whole complexity of the tasks we work with?

**Comment by haesleinhuepf** [comment]
Hi Johannes @jo-mueller ,

good idea! Before diving into details, I'd wonder what our visualization module would differentiate from libraries such as [bokeh](https://docs.bokeh.org/en/latest/docs/gallery.html) and [plotly](https://dash.gallery/Portal/). Furthermore, specifically for Bland-Altman plots there exist some nice implementations as shown here in [our teaching material](https://github.com/BiAPoL/Bio-image_Analysis_with_Python/blob/main/biostatistics/Bland_Altman_analysis.ipynb). Hence, I'm wondering if we should program a module for `biapol-utilities`, or if we should alternatively write a blog-post about how to use other tools. See also the blog post by Marcelo @zoccoler  about [jamovi](https://biapol.github.io/blog/marcelo_zoccoler/jamovi/jamovi)

**Comment by jo-mueller** [comment]
I had zero idea about bokeh. This looks great! Thanks for the tip. 

> Hence, I'm wondering if we should program a module for biapol-utilities

You are probably right about that. Maybe it would really be better suited to make a blog post about plotting in Python, including some of the non-matplotlib packages. This could then include:
- bokeh
- plotly
- seaborn

I'm closing this issue and will reopen an issue at the [blog page](https://github.com/BiAPoL/blog).
