### ISSUE TITLE
Program tests

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/biapol-utilities#9]
There are some functions which are not tested at the moment:

* [x] `label.intersection_over_union`
* [x] `label.label_overlap_matrix`
* [x] `label.match_labels_stack`
* [x] `label.match_labels`

Would be cool to have automatic tests for those

**Comment by jo-mueller** [comment]
Because I'm dumb - I accidentally put them to `biapol_utilities/tests` ^^"
